"""
Explainable AI Engine.

Creates clear, evidence-based and audit-ready explanations for decisions made
by the Dawlat AI Procurement & Global Trade Intelligence Platform.

The engine explains:
- why a decision was made;
- which evidence supported it;
- which controls passed or failed;
- which risks affected the outcome;
- which assumptions remain;
- which alternatives were considered;
- what would change the recommendation;
- what action should happen next.

It does not generate hidden chain-of-thought. It produces concise business
reasoning suitable for executive review, compliance, audit and human approval.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from models.decision import (
    EnterpriseDecision,
    RiskSeverity,
)
from services.intelligence.recommendation_intelligence_engine import (
    RecommendationReport,
    generate_enterprise_recommendations,
)
from services.intelligence.risk_intelligence_engine import (
    RiskAssessment,
    assess_enterprise_risk,
)
from services.intelligence.trust_intelligence_engine import (
    TrustAssessment,
    assess_enterprise_trust,
)


@dataclass(frozen=True)
class ExplanationEvidence:
    source: str
    label: str
    details: str
    record_id: int | None = None
    url: str | None = None
    verified: bool = False


@dataclass(frozen=True)
class ExplanationReason:
    category: str
    statement: str
    impact: str
    weight: int
    positive: bool


@dataclass(frozen=True)
class AlternativeOption:
    title: str
    description: str
    advantages: tuple[str, ...] = ()
    disadvantages: tuple[str, ...] = ()
    when_preferred: str = ""


@dataclass
class ExplainableDecision:
    decision_id: str
    title: str
    outcome: str
    executive_explanation: str
    confidence_score: int

    primary_reasons: list[ExplanationReason] = field(default_factory=list)
    supporting_evidence: list[ExplanationEvidence] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    blocking_reasons: list[str] = field(default_factory=list)
    assumptions: list[str] = field(default_factory=list)
    data_gaps: list[str] = field(default_factory=list)
    alternatives: list[AlternativeOption] = field(default_factory=list)
    next_actions: list[str] = field(default_factory=list)
    what_would_change_decision: list[str] = field(default_factory=list)
    audit_summary: dict[str, Any] = field(default_factory=dict)

    generated_at: str = field(
        default_factory=lambda: datetime.now().isoformat(timespec="seconds")
    )


class ExplainableAIEngine:
    """
    Converts enterprise decisions into transparent business explanations.

    The engine is deterministic and relies on the same decision, risk,
    recommendation and trust outputs already generated by the platform.
    """

    def explain(
        self,
        decision: EnterpriseDecision,
        *,
        risk_assessment: RiskAssessment | None = None,
        recommendation_report: RecommendationReport | None = None,
        trust_assessment: TrustAssessment | None = None,
    ) -> ExplainableDecision:
        risk = risk_assessment or assess_enterprise_risk(decision)
        recommendation = recommendation_report or (
            generate_enterprise_recommendations(
                decision,
                risk_assessment=risk,
            )
        )
        trust = trust_assessment or assess_enterprise_trust(
            decision,
            risk_assessment=risk,
        )

        reasons = self._reasons(
            decision=decision,
            risk=risk,
            recommendation=recommendation,
            trust=trust,
        )

        evidence = self._evidence(decision)
        alternatives = self._alternatives(
            decision=decision,
            risk=risk,
            recommendation=recommendation,
        )
        next_actions = self._next_actions(
            recommendation=recommendation,
            trust=trust,
        )
        change_conditions = self._change_conditions(
            decision=decision,
            risk=risk,
            trust=trust,
        )

        confidence = self._confidence(
            decision=decision,
            risk=risk,
            recommendation=recommendation,
            trust=trust,
            evidence=evidence,
        )

        return ExplainableDecision(
            decision_id=decision.decision_id,
            title=decision.title,
            outcome=trust.trust_decision.value,
            executive_explanation=self._executive_explanation(
                decision=decision,
                risk=risk,
                recommendation=recommendation,
                trust=trust,
                confidence=confidence,
            ),
            confidence_score=confidence,
            primary_reasons=reasons,
            supporting_evidence=evidence,
            risks=[
                item.description
                for item in risk.findings
            ],
            blocking_reasons=list(trust.blocking_reasons),
            assumptions=list(decision.assumptions),
            data_gaps=list(decision.data_gaps),
            alternatives=alternatives,
            next_actions=next_actions,
            what_would_change_decision=change_conditions,
            audit_summary=self._audit_summary(
                decision=decision,
                risk=risk,
                recommendation=recommendation,
                trust=trust,
                confidence=confidence,
            ),
        )

    @staticmethod
    def _reasons(
        *,
        decision: EnterpriseDecision,
        risk: RiskAssessment,
        recommendation: RecommendationReport,
        trust: TrustAssessment,
    ) -> list[ExplanationReason]:
        reasons: list[ExplanationReason] = []

        if decision.buyer_commitment:
            buyer = decision.buyer_commitment

            reasons.append(
                ExplanationReason(
                    category="Buyer",
                    statement=(
                        "Buyer acceptance and payment readiness are "
                        + (
                            "confirmed."
                            if (
                                buyer.accepted_in_writing
                                and decision.buyer_funds_cleared()
                            )
                            else "not fully confirmed."
                        )
                    ),
                    impact=(
                        "Directly controls whether supplier commitment is safe."
                    ),
                    weight=20,
                    positive=(
                        buyer.accepted_in_writing
                        and decision.buyer_funds_cleared()
                    ),
                )
            )

        if decision.supplier_offer:
            supplier = decision.supplier_offer

            reasons.append(
                ExplanationReason(
                    category="Supplier",
                    statement=(
                        f"Supplier {supplier.supplier_name} is "
                        + (
                            "verified."
                            if (
                                supplier.supplier_verified
                                and supplier.bank_details_verified
                            )
                            else "not fully verified."
                        )
                    ),
                    impact=(
                        "Affects fraud, quality, capacity and non-delivery risk."
                    ),
                    weight=20,
                    positive=(
                        supplier.supplier_verified
                        and supplier.bank_details_verified
                    ),
                )
            )

        if decision.margin_protection:
            margin = decision.margin_protection

            reasons.append(
                ExplanationReason(
                    category="Commercial",
                    statement=(
                        f"Expected margin is "
                        f"{margin.expected_margin_percent:.2f}% against a "
                        f"{margin.minimum_margin_percent:.2f}% minimum."
                    ),
                    impact="Determines whether Dawlat Global profit is protected.",
                    weight=20,
                    positive=margin.margin_protected,
                )
            )
        else:
            reasons.append(
                ExplanationReason(
                    category="Commercial",
                    statement="No approved margin analysis is available.",
                    impact="Profitability cannot be confirmed.",
                    weight=20,
                    positive=False,
                )
            )

        reasons.append(
            ExplanationReason(
                category="Risk",
                statement=(
                    f"Overall risk is {risk.overall_score}/100 "
                    f"({risk.overall_severity.value})."
                ),
                impact="Higher risk reduces readiness to proceed.",
                weight=15,
                positive=(
                    risk.overall_severity
                    in {
                        RiskSeverity.LOW,
                        RiskSeverity.MEDIUM,
                    }
                    and not risk.is_blocked
                ),
            )
        )

        reasons.append(
            ExplanationReason(
                category="Trust",
                statement=(
                    f"Overall trust score is {trust.overall_score}/100 "
                    f"with decision '{trust.trust_decision.value}'."
                ),
                impact=(
                    "Trust controls decide whether commitment or payment "
                    "is permitted."
                ),
                weight=15,
                positive=not trust.is_blocked,
            )
        )

        if recommendation.ranked_recommendations:
            top = recommendation.ranked_recommendations[0]

            reasons.append(
                ExplanationReason(
                    category="Recommendation",
                    statement=f"Highest-priority action: {top.action}",
                    impact="This is the most valuable next controlled action.",
                    weight=10,
                    positive=not top.blocking,
                )
            )

        reasons.sort(
            key=lambda item: (
                item.weight,
                item.positive,
            ),
            reverse=True,
        )

        return reasons

    @staticmethod
    def _evidence(
        decision: EnterpriseDecision,
    ) -> list[ExplanationEvidence]:
        evidence = []

        for item in decision.evidence:
            evidence.append(
                ExplanationEvidence(
                    source=item.source,
                    label=item.label,
                    details=item.details,
                    record_id=item.record_id,
                    url=item.url,
                    verified=bool(
                        item.verified_by
                        or item.document_hash
                    ),
                )
            )

        return evidence

    @staticmethod
    def _alternatives(
        *,
        decision: EnterpriseDecision,
        risk: RiskAssessment,
        recommendation: RecommendationReport,
    ) -> list[AlternativeOption]:
        alternatives: list[AlternativeOption] = []

        for text in recommendation.alternatives:
            alternatives.append(
                AlternativeOption(
                    title=text,
                    description=(
                        "Alternative identified by the enterprise "
                        "recommendation engine."
                    ),
                    advantages=(
                        "May reduce risk or improve commercial terms.",
                    ),
                    disadvantages=(
                        "May require additional time, verification or negotiation.",
                    ),
                    when_preferred=(
                        "Use when current controls, margin or trust are inadequate."
                    ),
                )
            )

        if decision.supplier_offer:
            alternatives.append(
                AlternativeOption(
                    title="Compare another verified supplier",
                    description=(
                        "Obtain at least one additional compliant offer."
                    ),
                    advantages=(
                        "Improves price discovery.",
                        "Reduces single-supplier dependency.",
                        "Provides negotiation leverage.",
                    ),
                    disadvantages=(
                        "May delay decision-making.",
                        "Requires more verification effort.",
                    ),
                    when_preferred=(
                        "Use when supplier risk, price or lead time is uncertain."
                    ),
                )
            )

        if risk.overall_severity in {
            RiskSeverity.HIGH,
            RiskSeverity.CRITICAL,
        }:
            alternatives.append(
                AlternativeOption(
                    title="Stop or defer the deal",
                    description=(
                        "Do not proceed until risk and trust conditions improve."
                    ),
                    advantages=(
                        "Protects cash, reputation and compliance.",
                    ),
                    disadvantages=(
                        "May delay revenue or lose the opportunity.",
                    ),
                    when_preferred=(
                        "Use when critical controls cannot be resolved."
                    ),
                )
            )

        unique: dict[str, AlternativeOption] = {}

        for item in alternatives:
            unique[item.title.strip().lower()] = item

        return list(unique.values())

    @staticmethod
    def _next_actions(
        *,
        recommendation: RecommendationReport,
        trust: TrustAssessment,
    ) -> list[str]:
        actions = [
            item.action
            for item in trust.outstanding_actions[:10]
        ]

        actions.extend(
            item.action
            for item in recommendation.ranked_recommendations[:10]
            if item.action not in actions
        )

        return actions[:15]

    @staticmethod
    def _change_conditions(
        *,
        decision: EnterpriseDecision,
        risk: RiskAssessment,
        trust: TrustAssessment,
    ) -> list[str]:
        conditions = []

        for item in trust.outstanding_actions:
            conditions.append(
                f"Decision may improve when: {item.action}"
            )

        if decision.margin_protection is None:
            conditions.append(
                "Decision may improve when a complete landed-cost and margin "
                "analysis is approved."
            )
        elif not decision.margin_protection.margin_protected:
            conditions.append(
                "Decision may improve when pricing or costs are renegotiated "
                "to protect the minimum margin."
            )

        if risk.is_blocked:
            conditions.append(
                "Decision may improve only after all blocking risk findings "
                "are resolved."
            )

        return list(dict.fromkeys(conditions))[:20]

    @staticmethod
    def _confidence(
        *,
        decision: EnterpriseDecision,
        risk: RiskAssessment,
        recommendation: RecommendationReport,
        trust: TrustAssessment,
        evidence: list[ExplanationEvidence],
    ) -> int:
        evidence_quality = min(
            20,
            sum(
                4 if item.verified else 2
                for item in evidence
            ),
        )

        score = round(
            decision.confidence_score * 0.25
            + risk.confidence_score * 0.20
            + recommendation.confidence_score * 0.20
            + trust.confidence_score * 0.25
            + evidence_quality * 0.10
        )

        score -= min(
            20,
            len(decision.data_gaps) * 4,
        )

        return max(0, min(100, score))

    @staticmethod
    def _executive_explanation(
        *,
        decision: EnterpriseDecision,
        risk: RiskAssessment,
        recommendation: RecommendationReport,
        trust: TrustAssessment,
        confidence: int,
    ) -> str:
        top_action = (
            recommendation.ranked_recommendations[0].action
            if recommendation.ranked_recommendations
            else "No ranked action is available."
        )

        supplier = (
            decision.supplier_offer.supplier_name
            if decision.supplier_offer
            else "No supplier selected"
        )
        buyer = (
            decision.buyer_commitment.buyer_name
            if decision.buyer_commitment
            else "No buyer confirmed"
        )

        return (
            f"Decision '{trust.trust_decision.value}' for buyer {buyer} and "
            f"supplier {supplier}. Confidence is {confidence}/100. "
            f"Overall risk is {risk.overall_score}/100 "
            f"({risk.overall_severity.value}); trust is "
            f"{trust.overall_score}/100. "
            f"There are {len(trust.blocking_reasons)} blocking issue(s). "
            f"Recommended next action: {top_action}"
        )

    @staticmethod
    def _audit_summary(
        *,
        decision: EnterpriseDecision,
        risk: RiskAssessment,
        recommendation: RecommendationReport,
        trust: TrustAssessment,
        confidence: int,
    ) -> dict[str, Any]:
        return {
            "decision_id": decision.decision_id,
            "decision_type": decision.decision_type.value,
            "decision_outcome": decision.outcome.value,
            "trust_decision": trust.trust_decision.value,
            "risk_score": risk.overall_score,
            "risk_severity": risk.overall_severity.value,
            "trust_score": trust.overall_score,
            "recommendation_status": (
                recommendation.recommendation_status
            ),
            "confidence_score": confidence,
            "evidence_count": len(decision.evidence),
            "risk_count": len(risk.findings),
            "blocking_count": len(trust.blocking_reasons),
            "assumption_count": len(decision.assumptions),
            "data_gap_count": len(decision.data_gaps),
            "generated_at": datetime.now().isoformat(
                timespec="seconds"
            ),
        }


_engine = ExplainableAIEngine()


def explain_enterprise_decision(
    decision: EnterpriseDecision,
    *,
    risk_assessment: RiskAssessment | None = None,
    recommendation_report: RecommendationReport | None = None,
    trust_assessment: TrustAssessment | None = None,
) -> ExplainableDecision:
    """Public explainability entry point."""

    return _engine.explain(
        decision,
        risk_assessment=risk_assessment,
        recommendation_report=recommendation_report,
        trust_assessment=trust_assessment,
    )